Add classes
OscarFMdev/OOP-library pull request #1
Opened 2022-12-20 21:38 UTC by OscarFMdev

# PR description: 📄 

In this PR I:

- Created Student, Person, and Teacher classes. 👤 
- Added README.md and LICENSE files. ✔️ 
- Added rubocop linters. 🤖 

### Thank you for reviewing my code! 🙌🏽

2022-12-20 23:24 UTC, codecaiine requested changes
Hi @OscarFMdev  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good class setup :heavy_check_mark: 
- No rubocop errors :heavy_check_mark: 
- Good use of gitflow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 23:24 UTC, codecaiine commented on person.rb
> +  attr_accessor :name, :age
- [ ] Good job so far but I would like to recommend you to declared your attributes before your method The attr method creates an instance variable and a getter method for each attribute name passed as argument . Check the example below and please fix it in order to make your app work as expected :+1: 

```
class Person 


  attr_accessor :name, :age

  attr_reader :id

  def initialize(age, name = 'Unkown', parent_permission: true)
    @id = Random.rand(1..1000)
    @name = name
    @age = age
    @parent_permission = parent_permission
  end

--------
The rest of your code 
--------
```

2022-12-20 23:24 UTC, codecaiine commented on student.rb
> +  attr_reader :id, :name, :age, :classroom
- [ ] Since a student Inherits from a Person I think it is not necessary to have these attributes declared here. Please remove them in order to make your app work as expected :+1:

2022-12-20 23:24 UTC, codecaiine commented on student.rb
> +  def initialize(classroom, age, name)
- [ ] Good job so far :clap:  But according to the project requirement you need to have a  Constructor with name, age, and parent_permission as parameters. name and parent_permission are optional and have default values of "Unknown" and true. and you should have Getters for @id, @name, and @age. And Setters for @name and @age. Please fix it in order to make your app work as expected :+1:

2022-12-20 23:24 UTC, codecaiine commented on teacher.rb
> +  attr_accessor :specialization, :age
- [ ] Since a teacher Inherits from a Person I think it is not necessary to have these attributes declared here. Please remove them in order to make your app work as expected :+1:

2022-12-20 23:24 UTC, codecaiine commented on teacher.rb
> +    super(age, name)
- [ ] Please make sure that you have  `parent_permission` set  true by default :+1:

2022-12-21 18:37 UTC, OscarFMdev commented on person.rb
> +  attr_accessor :name, :age
@codecaiine Thank you for the tip! I have fixed it

2022-12-21 18:43 UTC, OscarFMdev commented on student.rb
> +  def initialize(classroom, age, name)
@codecaiine I think this is for Person, it has a constructor using these specifications

2022-12-21 18:59 UTC, OscarFMdev commented
Thank you @codecaiine !

2022-12-21 19:04 UTC, t-yanick approved these changes
Hi @OscarFMdev, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 19:28 UTC, OscarFMdev commented
Thank you @t-yanick!

2022-12-21 19:28 UTC, merged