Associations
OscarFMdev/OOP-library pull request #3
Opened 2022-12-22 21:18 UTC by OscarFMdev

# PR Description 📄 

In this PR I:
- Created classes Classroom, Book and Rental 🏫 
- Added associations to these classes. ✅ 

### Thank you for reviewing my code! 🙌🏽

2022-12-22 21:41 UTC, mugishasam123 requested changes
Hi @OscarFMdev  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![alt](https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors 👍 
-  Descriptive Pr, keep rocking 🚀 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 21:41 UTC, mugishasam123 commented on student.rb
> +puts classroom1.add_student(student1)
- [ ] Please try to group operations in a method to make your code look clean .like you can create a method called `classroom` and you perform those operations:

```
 def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end

```

2022-12-22 22:35 UTC, OscarFMdev commented on student.rb
> +puts classroom1.add_student(student1)
@mugishasam123 thank you for letting me know!

2022-12-22 22:35 UTC, OscarFMdev commented on student.rb
> +puts classroom1.add_student(student1)
@mugishasam123 thank you for letting me know!

2022-12-23 00:29 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @OscarFMdev,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-23 01:57 UTC, OscarFMdev commented
Thanks @Omar-Muhamad !

2022-12-23 01:57 UTC, merged